### ISSUE TITLE
Error installing the package on Linux x64.

### ISSUE THREAD

**Issue by Andres6936** [Chris3606/GoRogue#10]
Morning.

I am a Linux user and when I try to install the package on Linux through NutGet I get the following output per console.

> Could not install package 'GoRogue 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have also tried to install the package in Mono. Net 2.0 as Mono. Net 4.7.1 and I still get the same error.

**Comment by Chris3606** [comment]
I'll test this on my end.  The error you're getting, I don't think it would work properly on .net 4.5, should require .net 4.6.1... But anything 4.6.1 or greater should work.  Even the newer versions of Mono tend to default to .NET 4.5 -- are you sure your project is targeting 4.6 or greater?

**Comment by Andres6936** [comment]
I had tested it on Mono. Net 4.5, now I have updated the project to version 4.6.1 Net Framework and continue with the error.

```
Adding GoRogue...
Installing 'GoRogue 1.0.0'.
Added file 'GoRogue.dll' to folder 'GoRogue.1.0.0/lib/netstandard2.0'.
Added file 'GoRogue.xml' to folder 'GoRogue.1.0.0/lib/netstandard2.0'.
Added file 'GoRogue.1.0.0.nupkg' to folder 'GoRogue.1.0.0'.
Successfully installed 'GoRogue 1.0.0'.
Adding 'GoRogue 1.0.0' to GoRogue.
Could not install package 'GoRogue 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

```

**Comment by Chris3606** [comment]
Odd.  I just tried adding it on Linux Mint x64 using MonoDevelop 7.1 build 1291 (Mono 5.4.1.6) and couldn't replicate it -- it added to a Mono 4.6.1 project just fine.  What version of Mono are you using?

**Comment by Chris3606** [comment]
I'll try to replicate the issue using MonoDevelop 5.1, however I suspect its an issue related to the older version of MonoDevelop.  .NET Standard 2.0 is definitely supported (according to the [.NET Standard docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) as of Mono 5.4.  That much said, If I remember correctly, MonoDevelop 5.1 by default installs and uses an older version of Mono.  It could also be an issue with the version of NuGet being used by that version of MonoDevelop.  Ideally I'd recommend updating your version of MonoDevelop (7.x branch is stable now).

If you have Mono 5.8 though, using Mono directly really should work, that part puzzles me -- that's another thing I'll try to replicate on my end.  In the mean-time, if you are perchance willing to update your version of MonoDevelop, let me know if that works.  Either way once I figure out how to replicate it on my end, I'll make sure to put some notes on it in my installation guide. :)

Thanks again!

**Comment by Andres6936** [comment]
I've spent the whole day trying to install MonoDevelop in its most recent version, I've had to install FlatPak, configure it, learn how to use the file to install MonoDevelop, until I've done it, right now I have MonoDevelop 7.3.3, however I haven't tried to install the package again, I will do it later because I've spent a lot of time installing MonoDevelop.

I'll write down the results later.

Thank you very much.

**Comment by Chris3606** [comment]
Another comment on this, I've been meaning to look into changing GoRogue to target a lesser version of .NET Standard anyway.  Technically it should target the lowest version it can, and I need to check to see what APIs exclusive to .NET Standard 2.0 (if any) are being used anyway.  If it is indeed possible for me to target .NET Standard 1.6 instead of .NET Standard 2.0, that may solve the compatibility issue as well (something else I'll be looking into).

**Comment by Andres6936** [comment]
Perfect, I managed to install the GoRogue package and it worked great on MonoDevelop 7.3, apparently the error comes from using MonoDevelop version 5.1.

**Comment by Chris3606** [comment]
Great to hear, glad you got it working!  I did look into targeting .NET Standard 1.6 (the version previous to 2.0), and unfortunately, due to the usage of Parallel and System.Tasks to multithread the current implementation of SenseMap, it will have to stay targeting .NET Standard 2.0 at the moment.
