### ISSUE TITLE
Map generation functions should return value types instead of System.Tuple

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#120]
System.Tuple was written at a time when c# value-tuples didn't exist -- value tuples are the intent here.

**Comment by masonwheeler** [comment]
Please be aware that not everyone is using C# 7, or even C# at all.  Value tuples are an extremely "magical" type that can cause some headaches if they're unsupported in your language.

**Comment by Chris3606** [comment]
Whoops, I do apologize -- this issue is a bit of a misnomer on my part (name will be edited shortly).  Value tuples (as in System.ValueTuple) are not exclusive to c# 7.0, they are defined as part of .NET Standard 2.0.  The "C# 7 value tuple" I refer to is actually referencing the c# 7.0 special syntax for those tuples, which if I'm not mistaken should resolve to System.ValueTuple implementation in other languages?

If you don't mind me asking, I am curious -- I definitely haven't given them a try in other languages, however given that System.ValueTuples are [part of .NET Standard 2.0](http://blog.monstuff.com/archives/2017/03/valuetuple-availability.html), I'm a bit confused as to what .NET Standard 2.0 compliant language doesn't support them?

**Comment by masonwheeler** [comment]
.NET Standard compliance refers to framework implementations, not languages.  It's true that any compiler capable of compiling against a framework that implements Standard 2.0 can work with `System.ValueTuple`, but the way C# does it, with names for the various members, is an illusion.  It's a hack implemented by the C# compiler that [puts the names in a special attribute,](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQFjZgZgQCY4BhOAbwzloSIAoBLAOwBc4APAGjgGU2AJ1YBzOAE8AlHACyDAJIARJgGcADgHsVAQwBGAGwCmcYKs06Dh6dXR07CAOxwGiXgCIAZho1vJ+OwC+GAFAA==) and if your compiler doesn't know to specifically look for this, all you're going to see is a `ValueTuple` without the context that makes it useful.

**Comment by Chris3606** [comment]
Right, that part I get.  I've never used value tuples as the type System.ValueTuple (just because I've never needed to), so maybe that's where the misunderstanding is.  However, if I'm not mistaken, all you lose if you need to use the type as System.ValueTuple, is the ability to access the parameters named, right (they become Item1, Item2, etc)?  Eg. [this type of code](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQFjZgZgQCY4BhOAbwzloSIAoBLAOwBc4APAGjgGU2AJ1YBzOAE8AlHACyDadXR1lCAOxwGiXgCIAZgHt92yfmUBfDBfQYoRKKSSqMigJC3sANgQ5ZAQ1YMSDAA2gC6cL6CIgDOkjR0iip0FAC24hQAvHAsAKYA7uTypklw8UlIAHQAar4ANgCuOQAq9QAOtTkAPKxsvALCLCIAfHAcWWlkFXImZXBuiACcDGwVAJJsOSmIcGCjaxspxCZ0s1ZmQA===)

**Comment by masonwheeler** [comment]
Yeah, it won't cause compilation issues.  I'm just kind of wondering why, since the biggest selling point of using ValueTuple is the added usability you get from putting names on the fields, and when people using your library are using languages where that's not supported, it's not a particularly useful thing to put in your public API.  (Especially if it will find some way of being a breaking change.  I haven't checked yet, but that's happened in the past.  Having the rectangle map generator vanish out from under me, for example!)

**Comment by Chris3606** [comment]
Rectangle map generator just moved to `QuickGenerators` (with the other generators, I believe) :D  Breaking changes can be a problem though, that's why this is tagged as a 3.0 issue (because in any case it would be a breaking change).  GoRogue follows semantic versioning (or tries to, and has done so a bit better recently I think), so breaking changes are allowed (an to be honest to some degree expected) in major version increments (1.x to 2.0, for instance, which I believe is where the map gen re-organization took place.)

As for value tuples in map gen -- the motivations are actually largely performance based for this change -- returning value types rather than System.Tuple (a reference type) means there are less of those expensive allocations, for a return value that the user may or may not even care about.  Value tuples specifically were just the most convenient item available, thus why the issue is named what it is.  Given the naming issues (which didn't occur to me until now), I could just as easily return some `struct` that implicitly converts to the right tuple, I believe, and get the same effect I was looking for without the pain in the neck value tuples directly might cause :D

**Comment by Chris3606** [comment]
Gah.  Actually, I think I may have moved a couple of functions into QuickGenerators before the 2.0 update, as part of the name deconfliction that came with a PR I merged...  Bad versioning on my part if that's the case, my bad.

**Comment by Chris3606** [comment]
Closed as subset of #186
