### ISSUE TITLE
Coord equality needs to be updated

### ISSUE THREAD

**Issue by masonwheeler** [Chris3606/GoRogue#137]
```
		public static bool operator ==(Coord c1, Coord c2)
		{
			if (ReferenceEquals(c1, c2))
				return true;

			if (ReferenceEquals(null, c1) || ReferenceEquals(null, c2))
				return false;

			return c1.X == c2.X && c1.Y == c2.Y;
		}
```

None of this but the last line makes any sense anymore, now that Coord is a struct, and all the boxing involved appears to be causing a noticeable performance hit.

**Comment by Chris3606** [comment]
Gah! Good catch, I thought I had changed this in the 2.0 update. Will put out a bugfix release for this as soon as I get the chance
