### ISSUE TITLE
Calling GenerateDungeonMazeMap without an IGenerator results in ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jeorgeashen** [Chris3606/GoRogue#150]
Overloaded function GenerateDungeonMazeMap in QuickGenerators can be called without passing an RNG parameter. However, doing so results in ArgumentOutOfRangeException inside RoomDoorConnector class. This doesn't happen in any other QuickGenerators function.

**Comment by Chris3606** [comment]
Thanks for letting me know!  I could swear I have a test case that calls them with the default generator, but I could be mistaken.  Either way, I probably won't be able to attempt to replicate this until tomorrow, but hopefully can get it fixed then.  In the mean-time, what are the parameters that you're passing to that function?  Does it happen every time you call that `QuickGenerators` function, or only on some generations?

**Comment by jeorgeashen** [comment]
First of all, parameters that are less likely to cause the problem. I use minRooms = 5, maxRooms = 40, minRoomSize = 10, maxRoomSize = 20 parameters when calling the function. I tried to change around the values as well as multiple generations., however that still caused an exception. 
For the first parameter I use an object of a class that implements the ISettableMapView<bool> interface. There is a tile array inside the class. Its values are set depending on the boolean values returned by the generator. Since all other generators work perfectly well (including the GenerateCellularAutomataMap which works with or without RNG parameter), I doubt the problem is due to wrong implementation of my class.

**Comment by Chris3606** [comment]
I figured, just wanted to make sure I'd be able to replicate it, as while I didn't think the other parameters were the direct cause, the relative density of rooms to size of map they create can sometimes make certain bugs more likely to appear, thanks to the amount of RNG involved.

I can definitely replicate it though, and at first glance I'm not sure why.  Either way, I'll dig into it later today and see if I can get a fix pushed out.  Thanks!

**Comment by Chris3606** [comment]
Fixed in 2.4.1, which was just released.  Thanks again!
