### ISSUE TITLE
FleeMap and GetDirectionOfMinValue

### ISSUE THREAD

**Issue by tstavrianos** [Chris3606/GoRogue#151]
Shouldn't the FleeMap reference the _goalMap field instead of _baseMap in the GetDirectionOfMinValue functions, since _baseMap is never updated in the FleeMap?

**Comment by Chris3606** [comment]
I'll double check when I can get to an environment that will let me test, but upon first glance, I believe you're correct. I'll look at this an fix/release tonight if so. Thanks!
