### ISSUE TITLE
UWP compatibility

### ISSUE THREAD

**Issue by Gavin-Williams** [Chris3606/GoRogue#153]
Is this library OK to use with UWP. I'm guessing it is as it's .net standard, but just wanted to check.

**Comment by Chris3606** [comment]
I'm so sorry, I somehow missed that this issue got created.  It should be ok, as pretty much anything .NET Standard should run with UWP.

**Comment by Gavin-Williams** [comment]
I haven't tried it yet. I've been rewriting my rendering and user interface and my game code hasn't been brought over yet. When i get everything working again I'll report  back.

**Comment by Chris3606** [comment]
Going to close this for now, as it seems to be working in a UWP environment from my end;  if you have any trouble with this, feel free to comment and we can revisit :D
