### ISSUE TITLE
VERY minor page edit?

### ISSUE THREAD

**Issue by sillydroid** [Chris3606/GoRogue#157]
Hi Chris,

Not sure if you meant it but the heading for Godot integration under Getting Started isn't formatted as a heading, and it's not in the table of contents on the right. Has a # in front of it.

Exceedingly minor tweak & sorry to bother you if that is what you intended. Just thought I'd mention in case you've got some Godot fans out there!

Cheers :-D

**Comment by Chris3606** [comment]
It sounds like it's probably a mistake, wouldn't be the first one :D.  Which page is this on?  Do you have a link?

**Comment by sillydroid** [comment]
Hi Chris,
Happy to help! It's on the Getting Started page https://chris3606.github.io/GoRogue/articles/getting-started.html?tabs=tabid-win (sorry should've included the link).

It looks like the "GoDot" section is meant to be formatted as a heading:

![image](https://user-images.githubusercontent.com/4340080/80566766-0b8f5a80-8a37-11ea-8be1-0a9fab519304.png)

Cheers! :-D

**Comment by Chris3606** [comment]
Got it - this will be fixed along with a bugfix released with 2.6.1 later today.  Thank you!
