### ISSUE TITLE
Region Code Cleanup

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#165]
Minor tidbits of code cleanup for `Region` code:
- Avoid use of `First()` and `Last()` when indexing into existing lists works (performance)
- Casts to `List` are no longer necessary; instead use private backing field that's already there
- Don't use try-catch in `operator!=` (performance)
- `IGenerator` should be taken as `IGenerator?` -- issue with nullable reference type warnings on other systems?
- Utilize pattern-matching in `Equals`
- Change `Rotate` to take origin as optional parameter defaulting to `Point.None` instead of `default(Point`), which works out to (0, 0).

**Comment by fcheadle** [comment]
> Change Rotate to take origin as optional parameter defaulting to Point.None instead of default(Point), which works out to (0, 0).

Point.None needs to be a compile-time constant in order for me to use it as a default value in an optional parameter. It doesn't even work when I try to declare a const in region like so:

`private const Point NoPoint = (int.MinValue, int.MinValue);`

I got around this by making the Origin no longer optional and adding a new Rotate function that doesn't take an origin. The new function passes in an "origin" that is the region's Center.
