### ISSUE TITLE
Add More MathHelpers

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#173]
@fcheadle has mentioned he has some additions to `MathHelpers` that would be useful.

In tandem with this, there is a `MathHelpers` library in GoRogue, as well as one in the primitives library; some to all of those may be able to be consolidated one way or the other.  Ideally there would be a clear distinction between the two.

**Comment by fcheadle** [comment]
After combing through my code, there is only one extension method I have left that I could contribute: `Rectangle` extensions for Recursive Bisection; I think that this strategy is also sometimes called Binary Space Partitioning.

**Comment by Chris3606** [comment]
Are these added via https://github.com/thesadrogue/TheSadRogue.Primitives/pull/48 in the primitives library?

**Comment by fcheadle** [comment]
Aye, the `Bisect` and related methods are the only things I had left that weren't already added.

**Comment by fcheadle** [comment]
The merge request has been accepted in the primitives library. I'm closing this issue as "complete"
