### ISSUE TITLE
Consider use of Direction in `ShiftX` functions in `Interpreter` for GoRogue debugger

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#179]
Currently, the functions calculate delta-x/delta-y for `_position` themselves and have a _invertY flag.  However, this is replicating functionality that already exists in direction: for example, we could simply do `_position += Direction.Up`, in the case of `ShiftUp`, and not have to worry about `_invertY` or actual delta numbers.

**Comment by fcheadle** [comment]
No problem! Added it to the next MR.

**Comment by Chris3606** [comment]
Forgot to close this; this was merged and is no longer an issue; and at any rate doesn't really apply after refactor in #196.
