### ISSUE TITLE
PR RotatePoint to PrimitivesLibrary and Potentially use in `Region.Rotate`

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#183]
Region contains a private function `RotatePoint` which is a prime candidate to move to `Point` in the primitives library.  This may also have implications for how `Region.Rotate` works; some performance tests are probably in order here.

**Comment by fcheadle** [comment]
See MR https://github.com/thesadrogue/TheSadRogue.Primitives/pull/47
GoRogue's changes are dependent upon that. I'm not going to be editing them much more than to delete the `RotatePoint` method from `Region`

**Comment by fcheadle** [comment]
Primitives contains the `Rotate` method, all thats left to do is remove it from region

**Comment by Chris3606** [comment]
Done in the linked PR above; as soon as I get that PR finished up it should be taken care of

**Comment by fcheadle** [comment]
Merge #206 has this fix, since I was in Region doing other stuff. This will be closed when that PR is approved.
