### ISSUE TITLE
Establish Consistency with Equality Comparisons, Mutable Types, and Region

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#184]
Currently, we have several different conventions being used for how to handle mutable objects and equality operators.

Some objects, like `Region`, have been set up to have the fields used in comparison and hash code read-only, at the potential expense of performance because it then requires certain operations to return a _new_ `Region` instance, which re-allocates a number of `Area` instances.

Some objects, like `Area` from the primitives library, which handles it incorrectly because it depends on a `HashSet`'s hashing function being different when different points are added: this is [a primitives library bug](https://github.com/thesadrogue/TheSadRogue.Primitives/issues/44).

A third convention, used by some complex GoRogue types, is to not provide equality operations at all on types where it is unlikely that the need to compare them would arise.

In any case, likely this should be solved the same way in the case of `Region`, other GoRogue types, and `Area`.

**Comment by fcheadle** [comment]
Let me know which style we're going to commit to, and I'll make the regions like so :)

**Comment by Chris3606** [comment]
@fcheadle Plan is to remove the equals, operator==, and GetHashCode implementations for `Region` and just implement the comparison using the new interface `IMatchable<Region>` released in the primitives library.  This is possible as of alpha6 of the primitives library, so is dependent upon [this PR](https://github.com/Chris3606/GoRogue/pull/204) which bumps the primitives library version.

**Comment by fcheadle** [comment]
Fix is included in PR #206 . Will be complete when that PR is accepted/closed
