### ISSUE TITLE
RandomRoomsGenerator is generating rooms that are too small

### ISSUE THREAD

**Issue by masonwheeler** [Chris3606/GoRogue#20]
Try running `RandomRoomsGenerator.Generate` on a decently-large map, with a large maximum number of rooms and a roomMinSize value of 4, and then have a look at the output that gets produced.  You'll see a lot of rooms that are only 2 or 3 cells wide/tall.

With larger minimum sizes, the effect can still be seen, with rooms frequently being produced up to 2 cells below the minimum in one or both dimensions.

This appears to be happening inside the `createRoom` method, where a 1-cell border on all sides is being excluded from the generated room.  Presumably this is to give rooms a wall, so you don't end up with one room pressed directly against another with nothing to separate them, but since a `bool` has no way to distinguish between a room wall and the dungeon interior, there is no way to make this distinction apparent, and instead you just end up with rooms that are smaller than the minimum for no easily-apparent reason.

If establishing the border wall is necessary, the internal logic should add 2 to the randomly-generated dimensions in order to account for it, rather than producing rooms that are too small.

**Comment by masonwheeler** [comment]
Awesome, thanks!

**Comment by Chris3606** [comment]
Fixed as of the 1.2.5 release.
