### ISSUE TITLE
AStar ShortestPath Exception

### ISSUE THREAD

**Issue by bloodyraoul** [Chris3606/GoRogue#35]
if the map have open borders (Walkability = true), ShortestPath try to find neighbours on the edges and raise an out of bound exception.
I dont know if it is intended so you force to use a map with borders or if it is a bug in the find neighbours methods that should test the bounds
Or maybe I dont use it the good way ;)
Thanks

**Comment by TimyJ** [comment]
If you had to check every cell to see if it was on an edge or not that would get kinda heavy wouldn't it? Idk. I just make sure the player never walks into the void. But am interested if there's a better way to handle that

**Comment by Chris3606** [comment]
I originally didn't consider an open map, it's never something I've used in a project.  However, the bounds should be checked to avoid throwing exceptions in these cases, I'll look into fixing this.

Offhand I'd actually say the bounds check isn't particularly heavy at all, and should not add much overhead, although it might affect performance a little.  It's something I'll look into as I'm adding it.

Thanks for the bug report!
