### ISSUE TITLE
Bounded Rectangle Area Doesn't Resize by -1

### ISSUE THREAD

**Issue by TimyJ** [Chris3606/GoRogue#43]
Tested extensively. Area will not resize by -1 if using MaxCorner arg. Any other value will result in a resize however. 
Example code:
```
 public void UpdateCameraSize(int dx, int dy)
        {
            Camera.Area = Camera.Area.NewWithMaxCorner(Coord.Get(dx + Camera.Area.Width, dy + Camera.Area.Height));
        }
```

**Comment by Chris3606** [comment]
This is actually a result of some very confusing naming conventions in Rectangle -- MaxCorner is the "last" position _included_ in the rectangle, which by definition is Camera.Area.Width - 1, not Camera.Area.Width.

There are a few naming changes that really need to happen in Rectangle; I'm about to make a new issue for them and can proceed discussion from there (I will cross-ref here)

**Comment by Chris3606** [comment]
See above cross-reference for issue about naming convention.  Also, edited given code example to make delta-specification clear, in case anyone encounters the same issue.
