### ISSUE TITLE
Change Rectangle Naming Conventions

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#44]
Properties in rectangle currently expose some very poorly named values, that can lead to confusing code.  See issue #43 for one example.  Proposal is as follows to correct:

- Rename MinCorner to Position, since it represents the "position" of the rectangle (we define rectangle position by its minimum extent)
    - Add MinExtent/MinExtentX/MinExtentY properties that are identical to Position/PositionX/PositionY, to be consistent with below convention
- Rename MaxCorner to MaxExtent, since it is talking about max extent of rectangle.
    - Rename MaxX/MaxY to MaxExtentX/MaxExtentY.
- Add Coord size Property that returns (Width, Height)
- Remove `Rectangle.NewWith...` functions, as the names are long and do not cover plausible use cases accurately. Replace them with with the following functions, all of which return new Rectangles with the specified changes made:
    - Move(int, int)/MoveTo(Coord) to move position
    - MoveX(int) to change X-value of position
    - MoveY(int) to change Y-value of position
    - Translate(int, int)/Translate(Coord) to move by given dx/dy
    - TranslateX(int) to move by given dx
    - TranslateY(int) to move by given dy
    - CenterOn(int, int)/CenterOn(Coord) to move center point
    - SetMinExtent(int, int)/SetMinExtent(Coord) to expand/shrink the rectangle to have the given MinExtent.
    - SetMinExtentX(int)/SetMinExtentY(int) to change the min extent values separately.
    - SetMaxExtent(int, int)/SetMaxExtent(Coord) to expand/shrink the rectangle to have the given MaxExtent.
    - SetMaxExtentX(int)/SetMaxExtentY(int) to change max extent values separately.
    - SetSize(int, int)/SetSize(Coord) to change the width/height of the rectangle to the specified values.
    - SetWidth(int)/SetHeight(int) to set the width/height separately to the specified values
    - ChangeSize(int, int)/ChangeSize(Coord) to change size by given dx/dy values
    - ChangeWidth(int)/ChangeHeight(int) co change height by given delta-values

**Comment by TimyJ** [comment]
Approve. The 'x'Extent stuff is a bit of a mouthfull but it is pretty precise so can't argue

**Comment by Chris3606** [comment]
> The 'x'Extent stuff is a bit of a mouthfull

Agreed, however I couldn't think of a better name that communicated that changing those values resizes the rectangle, rather than moving it.

**Comment by Chris3606** [comment]
This is implemented as of v1.4.3.
