### ISSUE TITLE
Method parameters with map generation

### ISSUE THREAD

**Issue by thomasd3** [Chris3606/GoRogue#53]
If you do a map with the cellular automata, you pass map, then the rnd gen as the second parameter, but if you use the room generator, the first parameter is the map, but the rnd gen is the last one.

I understand that since you can omit the random number generator, it has to be the last parameter.
What about adding several method signatures (with and without the rnd gen) to try to keep the parameters in the same order?

**Comment by Chris3606** [comment]
Agh.  Yep, I do see now that these are inconsistent.

I think I can work something out, either by using multiple method signatures to make sure the RNG is always the second parameter, or by assigning defaults to the other RandomRoomsGenerator parameters.

Thanks!

**Comment by Chris3606** [comment]
Will be released with 1.5.0.
