### ISSUE TITLE
Consider addition of SettablePositionalTranslationMap and equivalent lambda/ versions

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#65]
Currently, `TranslationMap` and `SettableTranslationMap` define their `TranslateGet`/`TranslateSet` functions to take only a value of type `T1`, and covert to value `T2`.  Particularly in the case of _settable_ implementations, it is often also necessary to know the position of the value being set.

I know this was a source of extra work for a user in a use case awhile back.  I do think it is relatively close to `LambdaSettableMapView` at that point.  At the same time, in almost all use-cases of Set involving complex source types I can think of, one would want the position as well.

It might be worth either adding some class like `SettableTranslationMap` that takes the position as well to its `TranslateSet`, or outright modifying `SettableTranslationMap` itself (albeit in v2.0.0 because of backwards compatibility issues)?

**Comment by tstavrianos** [comment]
What if you changed TranslationMap to this:
```
public abstract class TranslationMap<T1, T2> : IMapView<T2>
{
	...
	virtual public T2 this[Coord pos]
	{
		get => TranslateGet(pos, BaseMap[pos]);
	}
	...
	protected virtual T2 TranslateGet(T1 value)
	{
		throw new  NotImplementedException();
	}

	protected virtual T2 TranslateGet(Coord pos, T1 value)
	{
		return TranslateGet(value);
	}
}
```
That should allow you to not break the existing API, while also letting anyone that needs a positional translation to override the TranslateGet(Coord pos, T1 value) function instead of TranslateGet(T1 value).

**Comment by Chris3606** [comment]
I'll look into this, thanks!
