### ISSUE TITLE
FOV class enhancement

### ISSUE THREAD

**Issue by HooniusDev** [Chris3606/GoRogue#7]
Could we have ease of use fields ( NewlySeen, NewlyUnseen ) for FOV. At the time it is tedious to workout the Coords that enter/exit Fov so they can be marked as explored and inFov, I'm doing it in rendering.

[Example] https://github.com/darrellp/CSRogue/blob/master/CSRogue/Map%20Generation/FOV.cs

Great work all in all!

**Comment by Chris3606** [comment]
Shouldn't be terribly hard, and would definitely be useful to have. The only potential problem I see offhand is the example posted uses HashSets exclusively to store FOV, whereas my implementation (currently) uses 2d arrays. The only reason I wasn't using HashSet in the past was performance degredation n large cases in the past, however admittedly that was before the current Coord hash function. I'll play around with it and see if I can either replace the array with a hash set, or keep a hash set in addition.

Thanks!

**Comment by Chris3606** [comment]
Completed as per version 1.0.0.
