### ISSUE TITLE
Modify Coord to be a value type in instead of a pre-allocated pool

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#74]
Currently, `Coord` uses a pre-allocated pool of reference types, rather than being a value type, because nullable-value syntax, as well as syntax for exposing value-type properties, in C# was fairly rough around the edges.  However, this also creates some scalability issues, particularly when you want to use Coordinates over a much larger range than the standard (-3, -3) -> (255, 255) range.  Given that the brevity and simplicity of value-type related syntax has improved significantly in recent versions of C#, it may be worth making it a straight value-type in GoRogue 2.0.

**Comment by Thraka** [comment]
you also have the readonly ref with structs now and return refs too, to help prevent the defensive copying. So that is a good thing for struct perf in some cases. Though I'm not an expert in these things.

This is an amazing read on struct vs class vs boxing. I love it when I find articles like these. https://adamsitnik.com/Value-Types-vs-Reference-Types/

**Comment by Chris3606** [comment]
Long story short, as far as I can see, the syntax for dealing with structs (when you encounter cases like where structs are class members, etc) is fairly straightforward, _provided that the struct is immutable_.  It is of course recommended by Microsoft, and by most developers I've talked to, to avoid mutable structs wherever possible.  A mutable struct can create really, really irritating issues:

``` C#
class Coord // My values can be changed
{
    public int X;
    public int Y;

    public Coord (int x, int y)
    {
        X = x;
        Y = y;
    }

    public Coord SetValues(int newX, int newY)
    {
        X = newX;
        Y = newY;
    }
}

class Entity
{
    public Coord Position {get; set;}

    public Entity(Coord position)
    {
        Position = position;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var entity = new Entity(new Coord(1, 2));
        // Whoops!  Accessing the entity.Position property created a copy,
        // so I just modified the copy -- the original in the entity instance
        // remains unchanged.  No compiler error/warning to help either
        entity.Position.SetValues(100, 100);
    }
}
```

Something similar happens if you were to put the above `Coord` structure in a `List<Coord>` and tried to access it.  Thus, the struct would have to be immutable (readonly X and Y fields).  This isn't a big change, as this is the case in GoRogue's current implementation as well.

The only other issue, is that the most efficient way to expose a value type as a property in a class can vary -- sometimes, it is actually better to allow the defensive copying from a performance perspective, becuase using `ref` would actually cause the property to be boxed in a reference type every time its accessed (unless the compiler does some sneaky sneaky optimization in some cases, warrants research/testing).  This might have some implications to consider for some classes in `GoRogue` that expose `Coords` as properties.

**Comment by Chris3606** [comment]
I also should say, I would suspect that as far as the allocation piece goes, getting new Coords as structs would probably still be even faster than the pool method being used with reference types currently.  A few simplistic performance tests I ran awhile back seemed to confirm that.  I think the only real debate would be, whether or not to use `ref` to expose `Coord` instances as properties in `GoRogue` classes (which comes down to performance of boxing)

**Comment by Chris3606** [comment]
Whoa, ok -- I had to go digging through Intermediate Language on this one to clarify, however: the ref keyword, when used as the return of a property, does not box.  A ref property is precisely equivalent to a public value-type field -- it simply results in the value of a `ldflda` instruction (load field address), that grabs the address of the backing field, being returned to the user, just like the compiler would do if you accessed a field of a class.  Technically there is the overhead of a `callvirt` (virtual function call) that's used to call the property getter, however that is the expected overhead of properties to begin with, so no unexpected copy/overhead there.

As a side note, the issues with mutable structs are actually a lot worse than what my example indicated: because a property exposed as `ref` will implicitly copy the value if the variable it's stored in when retrieved isn't marked as `ref` as well, any time you interpret a struct ref as an interface, the value is first _copied_ via `ldobj`, then that _copy_ is boxed via the `box` instruction, and thus interpreted as the interface. So:
``` C#
interface ICoord // This is a stupid, pointless interface but only here for an example
{
    int X { get; set; }
    int Y { get; set; }
}

class Coord : ICoord // My values can be changed
{
    public int X { get; set; }
    public int Y { get; set; }

    public Coord (int x, int y)
    {
        X = x;
        Y = y;
    }

    public override string ToString() => $"({X},{Y})";
}

class Entity
{
    private Coord _position;
    public ref Coord Position => ref _position;

    public Entity(Coord position)
    {
        _position = position;
    }
}

class Program
{
    static void ModifyICoord(ICoord pos)
    {
        pos.X = 100; // Compiles fine...
    }
    static void Main(string[] args)
    {
        var entity = new Entity(new Coord(1, 2));
        // OUCH!  We copy the Position object, then box that copy, and pass
        // it to the function as an ICoord.  So, not only do we make a pointless
        // copy, but the ModifyICoord function doesn't change the original value --
        // it instead changes the copy
        ModifyICoord(entity.Position);

        // Value is still 1, 2
        Console.WriteLine(entity.Position);
    }
}
```

On an architecturally practical note.  Especially given `ref` and `readonly ref` return type additions, I think making `Coord` a value type, and value types in general, are fine, provided:
1. The value type is _not_ mutable.
2. The value type does not implement any interfaces

Given these two conditions, the worst that happens is someone exposes a property without using `ref`. 
 In the case of `Coord`, for example, this would only result in some pointless copying when you access the `X` and `Y` values of that `Coord` property.  When you set the value, it would still set properly.  If you pass them around to functions, you'll be doing a lot of copying, but it's generally copying to the stack, so it wouldn't be the worst thing in the world.  For those cases where you want to prevent that defensive copying, `ref` and `readonly ref` aren't too difficult to work with and do the job just fine.  Those could easily be integrated into any `GoRogue` classes that expose Coords, and again the worst that could happen is somebody stores the return value of that property in a field _not_ marked ref, which only results in a copy of two integers onto the stack in most cases.

**Comment by Thraka** [comment]
Trying to decipher this... :)

It sounds like that if the consumer doesn't ref the variable, they just get the same behavior they would get if the backing property wasn't ref: a copy. So that's not bad because it's the same behavior. However, if they do use ref, they may get some perf increase?

**Comment by Chris3606** [comment]
In short, yes.  If the consumer doesn't `ref` a local variable, they get a copy, which, if they're copying frequently, might lead to lesser performance.  Coord is a really small struct to begin with, so copies aren't quite as bad.

If the consumer doesn't ref a _property_, the copying can be a little more pronounced:

```C#
class Coord
{
    public readonly int X;
    public readonly int Y;

    public Coord (int x, int y)
    {
        X = x;
        Y = y;
    }
}

class Entity
{
   // NOT a ref property
    public Coord Position {get; set;}

    public Entity(Coord position)
    {
        Position = position;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var entity = new Entity(new Coord(1, 2));
        
        // This makes TWO copies of Position -- one each time we access the property.
        if (entity.Position.X < 0 || entity.Postion.Y < 0)
            Console.WriteLine("Invalid: has values less than 0.");
        else
            Console.WriteLine("valid!");
    }
```

Because auto-generated properties work by having a backing field and returning that field each time they're accessed, we can easily end up making more copies that we intend to.  But, it's still just coping a couple ints, so not the biggest deal.  It would only become a huge problem if:
1. The struct had mutable fields
2. The struct implemented an interface -- then we can end up copying AND boxing it, and that gets expensive -- boxing requires heap allocations.

**Comment by Chris3606** [comment]
This is in progress on local dev branch.  Note mostly for me, after the obvious compile-time errors due to Coord.Get being removed, I'll need to go through all uses in the library (yes, all... It hurts to think about) and see if any of them need to be converted to ref/readonly-ref syntax...
