### ISSUE TITLE
Add Interface IMoves Support to Spatial Maps

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#75]
Currently, SpatialMap implementations require you to pass the position of an object in when it is added, and call the Move function whenever it moves.  This can be inconvenient, since nearly any object that is going to be placed in a SpatialMap will record its own position anyway.

As such, these implementations could be modified to require a Position field and Moved event of their objects, and do the updating manually.  This would require throwing exception if the move is invalid, unless the move event allowed cancellation.

**Comment by Chris3606** [comment]
As an extended example of an issue; let's say we have the `SomeMapThing` class, which is a relevant subsection of SadConsole's `Entity`:
``` C#
class SomeMapThing
{
    public Point Position { get; set; } // MonoGame point
   // (Other stuff)
}
```

Now, if we have an interface that GoRogue requires `SpatialMap` objects to implement, say:
``` C#
interface IHasPosition
{
    Coord Position { get; } 
    event EventHandler Moved;
}
```

We create a version of `SomeMapThing` that can go into `SpatialMap` with:
``` C#
class NewMapThing : SomeMapThing, IHasPosition
{
   // Name is the same as the SomeMapThing.Position property so we have to implement explicitly
    public Coord IHasPosition.Position
    {
        get => base.Position.ToCoord(); // Some extension function that converts Point to Coord
        set
        {
            if (base.Position.ToCoord() != value)
            {
                base.Position = value.ToPoint(); // Coord to Point conversion function
                Moved?.Invoke(this, EventArgs.Empty);
            }
        }
    }
    // Makes sure setting this invokes the move event
    public new Point Position
    {
        get => base.Position;
        set => ((IHasPosition)this).Position = value.ToCoord();
    }
}
```

While this would allow the implementation of `ISpatialMap` in a way that did not require using the `Move` function to keep in sync, this implementation has a few problems, IMO:
1. If someone sets `SomeMapThingInstance.Position`, with that object held in a reference of type `MyMapThing`, the Moved event is not invoked.
    - The fix for this would be for `MyMapThing.Position` to be virtual, and we use `override` instead of `new`.  However, this results in GoRogue requiring things of other libraries to be able to integrate, which I am not a fan of.
2. This implementation is extremely verbose, requiring uses of what I would qualify as obscure/easy-to-mess-up-with features of C# (explicit interface implementation, `new` property keyword), which IMO makes it less user-friendly.

Thus, personally I think I'm more a fan of keeping the requirement as-is.  Particularly in the case where an integration library is involved, it is a bit of work, but easily possible, to transparently call the `Move` function whenever a `Position` is set (it only requires that the position setter ensure that the `Move` function does not fail), or to do the opposite (set the `Position` whenever an object moves), which I feel like is a more flexible set of options.

**Comment by Thraka** [comment]
This is a tough one. Let me think on it. 

One other scenario to account for is having the object in two different spatial maps at the same time? Is that possible? I was thinking about this in the sense of having a single spatial map representing all objects on the map right? But then you have a 2nd map representing all monsters or items within 10 spaces of the character. If the player moves, both maps need to update. So using a single map to update the player does't exactly work correctly because if you change player via map1, map2 is now out of sync.

**Comment by Chris3606** [comment]
This is a good point -- it is certainly possible to have an item in more than one spatial map, generally speaking.  In the current system, this would simply be a matter of moving the items in both spatial maps (call two `Move` functions), or hook the spatial map's `ItemMoved` events together in such a way that if you move one, the other `Move` is called as well (`ISpatialMap` will make sure the position has actually changed before it fires the `ItemMoved` event, so no infinite loop, as of the fix for issue #84).  Another option (and the one I typically go with) is, if the objects in the `SpatialMap` record their position (eg, have a position field) and a Moved event, you can take whatever `Map` class you put the `SpatialMap` in, and as entities are added, put a handler in their `Moved` event that calls `Move` in the `SpatialMap` instances.

In the example I wrote above, it gets a bit more tricksie to pull off, but works basically the same as the one I described above.  I do think that it becomes a bit less obvious what's going on in that case, however.

**Comment by Thraka** [comment]
I did happen to design SadConsole with an `OnPositionChanged` method that is called when the position changes 😄 The whole `new property` with having two properties named the same is a terrible way to design around the issue. But it's a necessary evil 😄 that I'm glad I foresaw with `OnPositionChanged` 

```csharp
protected virtual void OnPositionChanged(Point oldLocation) { }
```

So in the case of SadConsole, you could merge your design with mine and have something pretty simple.

```csharp
class NewMapThing : Entities.Entity, IHasPosition
{
    private Coord _roguePosition;

    // Name is the same as the SomeMapThing.Position property so we have to implement explicitly
    public Coord IHasPosition.Position
    {
        get => _roguePosition;
        set
        {
            if (_roguePosition != value)
                Position = value.ToPoint(); // Set the real master position
        }
    }

    protected override void OnPositionChanged(Point oldLocation)
    {
        // if points don't match, spatial map needs update (or anything who subscribed to moved)
        if (_roguePosition != Position.ToCoord())
        {
            _roguePosition = Position.ToCoord();
            Moved?.Invoke(this, EventArgs.Empty);
        }
    }
}
```

The `Moved` event design does seem nice. It allows the programmer to decide when to notify the move. And with the interface the GoRogue point can be hidden without issue. Also, if you had someone using GoRogue with nothing else, they can just as easily implement `IHasPosition.Position` implicitly and have that be the pure way for positioning. So `Moved` lets you integrate better with others like SadConsole.

Either way, when you have the scenario of there being two types of positioning properties, something tricky has to be designed 😄 So I wouldn't let that hold back a good design that makes that tricky part easier, like `Moved`.

**Comment by Chris3606** [comment]
This is true.  The above solution, provided `OnPositionChanged` is called properly when the master position changes, works well.  That much said, one could take the current implementation and above class (with the moved event), and create something like:

``` C#
public Map
{
    SpatialMap<NewMapThing> _mapThings;

    public void AddThing(NewMapThing thing)
    {
        if (_mapThings.Add(thing))
            thing.Moved += OnThingMoved;
    }

    public void RemoveThing(NewMapThing thing)
    {
        if (_mapThings.Remove(thing))
            thing.Moved -= OnThingMoved
    }

    private void OnThingMoved(object s, EventArgs e)
    {
       var mapThing = (NewMapThing)s;
        _mapThings.Move(mapThing, mapThing.Position); // Provided this returns the NEW position 
    }
}
```

And get the same effect, with I believe about the same amount of work. (?)  The small problem with this implementation, and the example you posted, is that if the master position changes in a way that the SpatialMap won't allow (eg. something that causes Move to return false), the spatial map has no method of rejecting that change.  The solution is, of course, to make sure this doesn't happen in your implementation of the setter.  I must say, though, I do believe this is more obvious when the `SpatialMap.Move` function exists.  I'm not really sure which is the more intuitive solution there.

**Comment by Chris3606** [comment]
That's not a bad thought at all. I'll come back to this when I can get to a computer and do some playing around

**Comment by Thraka** [comment]
I'm still trying to figure this one out.. what to do.. what to do..

**Comment by Chris3606** [comment]
I still haven't been able to come up with a super satisfactory solution to this.  I'm thinking if anything, it would just come to implementing a version of the spatial maps that does the linking of move events to the `Move` function for you, and throws exception if that move happens to somewhere it should't -- the current system of `Move` functions returning `false` when they fail is something I aim to change anyway so that they throw exceptions, however that's a breaking change.  As such, particularly with the additions of somewhat limited use in the immediate future (as the GoRogue SadConsole integration library shows, it' isn't difficult and is arguably more intuitive to just wrap the `Move` call into internals of a `Map` class, I'll probably push this to 3.0/3.x

**Comment by Chris3606** [comment]
Since the changes to spatial maps in 3.x, this would just amount to creating an interface which defines a position and a Moved event (or perhaps just a moved event), and auto-registering a handler for that event which performs the move syncs.

**Comment by Chris3606** [comment]
Closing this as spatial maps are moving to the primitives library; this issue is now tracked [here](https://github.com/thesadrogue/TheSadRogue.Primitives/issues/116) and further discussion should take place there.
