### ISSUE TITLE
Change Direction functions to return Coords representing neighbors instead of directions

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#8]
Currently, we have functions like CardinalsClockwise, DirectionsClockwise, etc. that return 4 or 8 directions in a particular order.  The most common/main use for such a function is presumably to visit all neighbors of a given Coord:

```C#
Coord start = Coord.Get(1, 2);
foreach (Direction dir in Direction.DirectionsClockwise())
{
    Coord neighbor = start + dir;
    // Do things with the neighbor.
}
```

Under these circumstances, it would seem to be more beneficial to instead have functions that take a Coord and return neighbors of that Cood:

```C#
Coord start = Coord.Get(1, 2);
foreach (Coord neighbor in Directions.Neighbors(start))
{
    /// Do things with neighbor
}
```

In this case, perhaps such a series of function would also be more logically located in the Coord class, rather than the Direction class.

Any thoughts, or possible cases where functionality might be removed by making this change, are welcome in the comments.

**Comment by HooniusDev** [comment]
Sounds good. The neighbouring Coords should definitely live inside the Coord class. I mainly use/plan to use Directions for moving things one Coord at a time. 
Don't recall if it's already there, I would like Direction to have things like TurnLeft, which would give me the CounterClockwise neighbor (Cardinal or Diagonal should be specified somewhere).
When I get to my PC I'll try to proof read this.

**Comment by Chris3606** [comment]
Direction does already have these more or less -- in the form of addition and subtraction operators:

```C#
Direction dir = Direction.UP;
dir--; // dir is now UP_LEFT (next clockwise direction)
dir++; // dir is now UP (next counterclockwise direction)

dir = dir + 2; // dir is now RIGHT (next cardinal clockwise direction)
```

I believe that is what you were looking for :)

Thanks!

**Comment by Chris3606** [comment]
Likely will implement neighbors functions in Coord as specified, but also leave the existing Direction functions in-place.  This will help prevent breaking backwards compability, and as well, functions returning the actual directions are desireable in at least the case of shadowcasting as implemented by GoRogue's FOV and SenseMap classes, and as such may be useful elsewhere as well.
