### ISSUE TITLE
Add 1D indexers to map view interface

### ISSUE THREAD

**Issue by Chris3606** [Chris3606/GoRogue#86]
Currently, Coords provide a ToIndex function, and MapView implementations only implement the Coord/int x, int y indexers.  This works well, however is inconvenient when you want to access a `MapView` like it is a 1D array.  An indexer could be added to the interface that allows accessing the `MapView` like it is a 1D array.

Unfortunately, since default interface implementations in C# do not exist until C# 8.0 (release sometime 2019), this would require changes to any existing custom `IMapView` implementations.  However, things like `LambdaMapView` and others could be easily modified to only take their current functions, and simply implement the indexers by performing translation to 1D indexes.

**Comment by Thraka** [comment]
Can you use SPAN for this?

**Comment by Chris3606** [comment]
Could I expose an ArrayMap as a Span, or a slice of an ArrayMap as a Span? Yes, though it might require me to make the backing array 1d instead of 2d (which wouldn't be the biggest deal).

However, since Span by definition must represent contiguous memory, this wouldn't really apply to any `MapView` that isn't an `ArrayMap`, or backed by an actual array.

**Comment by Chris3606** [comment]
One thing I have thought about doing, is exposing the backing array for an ArrayMap to the user.  It would allow leveraging things like Span when you know you are dealing with ArrayMaps. If I exposed a constructor for ArrayMap that also let you pass in an existing array, it might (not sure?) make it a little easier to use with SadConsole in places...

**Comment by Thraka** [comment]
That would be good. Also I think with span, you can't set stride, so it won't help for sub areas of an end-to-end map, For example a map that is 100 x 100 you cant span and view 20, 20, 40, 40.
