### ISSUE TITLE
Compatible .Net versions not documented

### ISSUE THREAD

**Issue by TimyJ** [Chris3606/GoRogue#97]
Docs are unclear about what the minimum supported .Net framework version is. Would be helpful for new project setup if this was listed in the getting started pages as visual studio 2017 does not create c# projects with a compatible version.

**Comment by Chris3606** [comment]
I went ahead and added this information to the getting started pages.  I will leave this issue open, though, as there are some other spots in the documentation that need some tweaking in this regard (the readme, etc).  Those other changes will probably be made along with the GoRogue 2.0 documentation changes, of which there are many...

**Comment by Chris3606** [comment]
This is added on the new docs site, forgot about this issue. Closing...
